all:
	gcc main.c ../libevent-2.0.20-stable/.libs/libevent.a -I ../libevent-2.0.20-stable/include/event2/ -o main
	gcc main2.c ../libevent-2.0.20-stable/.libs/libevent.a -I ../libevent-2.0.20-stable/include -I ../libevent-2.0.20-stable/include/event2/ -o main2
	gcc main3.c ../libevent-2.0.20-stable/.libs/libevent.a -I ../libevent-2.0.20-stable/include -I ../libevent-2.0.20-stable/include/event2/ -o main3
